version: "1.0"

services:
  db:
    image: postgres:16-alpine
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: e-commerce
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5433:5432" # Porta mapeada para acesso local

  api:
    build: .
    ports:
      - "3001:3001"
    environment:
      # Aponte o DATABASE_URL para o serviço 'db' no Docker
      DATABASE_URL: "postgresql://postgres:postgres@db:5432/e-commerce"
      JWT_SECRET: "sdoahdoawdaw56as4d564aw56d46as5dasd546" # Demais variáveis
      # ... (Cloudinary, Mercado Pago, etc.)
    depends_on:
      - db
    # Comando para rodar migrações antes de iniciar
    command: sh -c "npx prisma migrate deploy && node dist/app.js"

volumes:
  postgres_data:
